In [1]:
import torch
import time
import numpy as np
import torch.nn as nn
from torch.nn import functional as F
device = "mps" if torch.backends.mps.is_available() else "cpu"

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 37,  19, -63,  76,  27,  72])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [0.2, 2.4], [0.3, 3.6]])
tensor

tensor([[0.1000, 1.2000],
        [0.2000, 2.4000],
        [0.3000, 3.6000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
arange = torch.arange(5, 0, -1)
arange

tensor([5, 4, 3, 2, 1])

In [8]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
f"{elapsed_time:.8f}"

CPU times: user 230 µs, sys: 185 µs, total: 415 µs
Wall time: 291 µs


'0.00025702'

In [13]:
# Creating 4-dimensional tensors with random values using PyTorch and moving them to the GPU (if available)
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)

# Creating 4-dimensional arrays with random values using NumPy (which will be processed on CPU)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

# Recording the start time for PyTorch operation
start_time = time.time()

# Performing matrix multiplication on the PyTorch tensors (on GPU)
rand = (torch_rand1 @ torch_rand2)

# Recording the end time for PyTorch operation
end_time = time.time()

# Calculating and printing the elapsed time for the PyTorch operation (on GPU)
elapsed_time = end_time - start_time
print(f"Time elapsed for matrix multiplication in PyTorch (on GPU): {elapsed_time:.8f} seconds")

# Recording the start time for NumPy operation
start_time = time.time()

# Performing element-wise multiplication on the NumPy arrays (on CPU)
rand = np.multiply(np_rand1, np_rand2)

# Recording the end time for NumPy operation
end_time = time.time()

# Calculating and printing the elapsed time for the NumPy operation (on CPU)
elapsed_time = end_time - start_time
print(f"Time elapsed for element-wise multiplication in NumPy (on CPU): {elapsed_time:.8f} seconds")

Time elapsed for matrix multiplication in PyTorch (on GPU): 0.05744386 seconds
Time elapsed for element-wise multiplication in NumPy (on CPU): 0.06842375 seconds


In [14]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [15]:
tensor = torch.tensor([i for i in range(1,5)])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [16]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [17]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [18]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [19]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [20]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [21]:
tensor1 = torch.tensor([1,2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
linear(sample)

tensor([ 2.9142, -6.8454, -9.1649], grad_fn=<SqueezeBackward4>)

In [23]:
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()

softmax_output = F.softmax(tensor1, dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [24]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 0.2427,  0.3078, -0.9586, -0.8609, -0.1617,  0.6513],
        [ 0.1751,  0.2406, -0.6411,  0.7451,  0.1621,  1.6844],
        [ 0.9057, -0.5624, -0.4269, -0.1799,  1.9620,  0.2019],
        [-0.9693, -0.0925, -0.3055, -0.6328,  0.1302, -0.1691]],
       grad_fn=<EmbeddingBackward0>)


In [25]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)
torch.matmul(a, b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [26]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64
float_32 = torch.rand(2,3)
#type float32
# print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [28]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x, y, z)
print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])
