In [1]:
import torch
import time
import numpy as np
import torch.nn as nn
from torch.nn import functional as F
device = "mps" if torch.backends.mps.is_available() else "cpu"

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 28,  27,  55,  12,  21, -39])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [0.2, 2.4], [0.3, 3.6]])
tensor

tensor([[0.1000, 1.2000],
        [0.2000, 2.4000],
        [0.3000, 3.6000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
arange = torch.arange(5, 0, -1)
arange

tensor([5, 4, 3, 2, 1])

In [8]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
f"{elapsed_time:.8f}"

CPU times: user 93 µs, sys: 23 µs, total: 116 µs
Wall time: 115 µs


'0.00006676'

In [13]:
# Creating 4-dimensional tensors with random values using PyTorch and moving them to the GPU (if available)
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)

# Creating 4-dimensional arrays with random values using NumPy (which will be processed on CPU)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

# Recording the start time for PyTorch operation
start_time = time.time()

# Performing matrix multiplication on the PyTorch tensors (on GPU)
rand = (torch_rand1 @ torch_rand2)

# Recording the end time for PyTorch operation
end_time = time.time()

# Calculating and printing the elapsed time for the PyTorch operation (on GPU)
elapsed_time = end_time - start_time
print(f"Time elapsed for matrix multiplication in PyTorch (on GPU): {elapsed_time:.8f} seconds")

# Recording the start time for NumPy operation
start_time = time.time()

# Performing element-wise multiplication on the NumPy arrays (on CPU)
rand = np.multiply(np_rand1, np_rand2)

# Recording the end time for NumPy operation
end_time = time.time()

# Calculating and printing the elapsed time for the NumPy operation (on CPU)
elapsed_time = end_time - start_time
print(f"Time elapsed for element-wise multiplication in NumPy (on CPU): {elapsed_time:.8f} seconds")

Time elapsed for matrix multiplication in PyTorch (on GPU): 0.24031997 seconds
Time elapsed for element-wise multiplication in NumPy (on CPU): 0.06417990 seconds


In [14]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 0, 1, 1, 1, 1, 1, 1])


In [15]:
tensor = torch.tensor([i for i in range(1,5)])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [16]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [17]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [18]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [19]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [20]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [21]:
tensor1 = torch.tensor([1,2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
linear(sample)

tensor([-7.7188, -3.0890, -9.0590], grad_fn=<SqueezeBackward4>)

In [23]:
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()

softmax_output = F.softmax(tensor1, dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [24]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[-1.0139, -0.7598, -0.2625, -0.8895, -1.4543, -0.0653],
        [ 1.6604, -0.5045, -0.2390,  0.5943,  0.1224,  0.1695],
        [ 0.4318, -0.6426, -1.2963, -0.1137, -0.5726,  0.5643],
        [-1.2703, -0.2399, -0.7055, -1.0866,  0.8410,  0.4732]],
       grad_fn=<EmbeddingBackward0>)


In [25]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)
torch.matmul(a, b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [26]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64
float_32 = torch.rand(2,3)
#type float32
# print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [27]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x, y, z)
print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])


In [29]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
print(output[:, -1])

tensor([[0.8892, 0.8029, 0.1223, 0.5366, 0.6287, 0.5056, 0.0818, 0.4684, 0.4939,
         0.6717],
        [0.6018, 0.8644, 0.2913, 0.1024, 0.9553, 0.0642, 0.6773, 0.4367, 0.1611,
         0.3566],
        [0.7605, 0.4782, 0.0895, 0.6823, 0.3223, 0.7513, 0.1786, 0.4007, 0.8553,
         0.8619],
        [0.8324, 0.5864, 0.1560, 0.2860, 0.1532, 0.3100, 0.4418, 0.6924, 0.9610,
         0.6388],
        [0.9194, 0.6265, 0.2697, 0.1950, 0.6156, 0.8504, 0.5275, 0.0667, 0.2289,
         0.7629],
        [0.3615, 0.9601, 0.1102, 0.9120, 0.2369, 0.6282, 0.1782, 0.3555, 0.0054,
         0.9023],
        [0.9911, 0.7474, 0.8178, 0.7834, 0.1543, 0.9319, 0.1335, 0.2472, 0.2095,
         0.9135],
        [0.3333, 0.5584, 0.9322, 0.3099, 0.1152, 0.7318, 0.3519, 0.5298, 0.2700,
         0.3501],
        [0.6543, 0.2202, 0.3062, 0.2408, 0.4184, 0.4250, 0.8027, 0.6229, 0.7700,
         0.5117],
        [0.7494, 0.3114, 0.7774, 0.6869, 0.9152, 0.9405, 0.2975, 0.8729, 0.1269,
         0.2312],
        [0

In [33]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])
